/* File defines set of tests
 * Programs in tests/ should match pass all these lines
 */
#pragma once
#include <cstdint>

struct AlignmentTest {
  const char *name;
  const char *ref; // note ref and query are parsed as uint8_t almost immediately
  const char *query;
  uint32_t ref_len;
  uint32_t query_len;
  const char *build_dir; // path to build/<r>x<q>/ containing final.xclbin and insts.bin
};

#define ATEST(name, ref, query, build_dir) \
  { name, ref, query, (int)__builtin_strlen(ref), (int)__builtin_strlen(query), build_dir }

// --- 16x16 tests ---
static const AlignmentTest tests16x16[] = {
  ATEST("basic_16x16", "TGAAATTTTGTTGCAG", "TGACTTTGCTATGCAG", "build/16x16"),
  ATEST("exact_16x16", "ACCAACACTGGATTGC", "ACCAACACTGGATTGC", "build/16x16"),
  ATEST("oppst_16x16", "AAAATTTTAAAATTTT", "CCCCGGGGCCCCGGGG", "build/16x16"),
  ATEST("ATCG_16x16" , "AAAATTTTCCCCGGGG", "GGAAAATTTTCCCCGG", "build/16x16"),
};

// --- 32x32 tests ---
static const AlignmentTest tests32x32[] = {
  ATEST("ATCG_32x32"       , "TTTTCACTTAAAGTATTATGCACGACAGGGTG", "CGTGTACCATGTAAACCTGTTATAACTTACCT", "build/32x32"),
  ATEST("ATCG2_32x32"      , "TGAAAGCCAGTTGGTGTTAAGGGGTGCTCTGT", "CCAGGACGCCACGCGTAGTGAGACTTACATGT", "build/32x32"),
  ATEST("AT_content0_32x32", "ATTAAAAATATATTTAAATTTTAAATTTTATT", "ATTAAAAAATATATATTTTATTTTTATAATTT", "build/32x32"),
};

// --- 32x64 tests ---
static const AlignmentTest tests32x64[] = {
  ATEST("ATCG_32x64",
        "TTTTCACTTAAAGTATTATGCACGACAGGGTG",
        "CGTGTACCATGTAAACCTGTTATAACTTACCTCGTGTACCATGTAAACCTGTTATAACTTACCT",
        "build/32x64"),
};


// --- 80x80 tests ---
static const AlignmentTest tests80x80[] = {
  ATEST("ATCG1_80x80",
        "GACACGCGTCTCCTTGCGGGTAAATCGCCGACCGCAGAACTTACGAGCCAGGGGAAACAGTAAGGCCTAATTAGGTAAAG",
        "ACGAGATTTGAGGTAAACCAAATGAGCACATAGTGGCGCTATCCGACTATTTCCAAATTGTAACATATCGTTCCATGAAG",
        "build/80x80"),
  ATEST("ATCG2_80x80",
        "TTCATACCGCTCATTCACTAGGTTGCGAAGTCTACACTGATATATGAATCCGAGCTAGAGCAGGGCTCTTAAAATTCGGA",
        "AAGGCTCAGAGTGCAGACTGGAGCGCCCATCTAACGGTTCGCATCTCGAATGCTCGGTCGCCTTTCACATTCCGCGAAAA",
        "build/80x80"),
};

// --- 88x88 tests ---
static const AlignmentTest tests88x88[] = {
  ATEST("ATCG1_88x88",
        "GACACGCGTCTCCTTGCGGGTAAATCGCCGACCGCAGAACTTACGAGCCAGGGGAAACAGTAAGGCCTAATTAGGTAAAGAATTCCTA",
        "ACGAGATTTGAGGTAAACCAAATGAGCACATAGTGGCGCTATCCGACTATTTCCAAATTGTAACATATCGTTCCATGAAGGATCTAGC",
        "build/88x88"),
  ATEST("ATCG2_88x88",
        "TTCATACCGCTCATTCACTAGGTTGCGAAGTCTACACTGATATATGAATCCGAGCTAGAGCAGGGCTCTTAAAATTCGGACGATCCTC",
        "AAGGCTCAGAGTGCAGACTGGAGCGCCCATCTAACGGTTCGCATCTCGAATGCTCGGTCGCCTTTCACATTCCGCGAAAACGAGCATC",
        "build/88x88"),
};

// --- 60x132 tests ---
static const AlignmentTest tests60x132[] = {
  ATEST("ATCG1_60x132",
        "GTGTACAAGTAATTGTCAACAGACCATCGTGTTTTCATAATGGTACCAGGATCTTCAAGC",
        "ACTTGTACCCAACCCCCGAAGTTTAGCAGGTCGTGGGGTGTCATGGAGCCTCTGGTTCATCCCGTGGGATATCAAGCTTCGTCTTGATAAAGCTCCCCGCTCGGGTGTAGCAGAGAAGACGCCTACTGAATT",
        "build/60x132"),
  ATEST("ATCG2_60x132",
        "CGTGTCAATCAAGCTCGGATTACGGTGTTTACTCCGTCCTGCGGTTACTCACGGTCTGTA",
        "ATCCACCTCAAGTCAAGCCATTGCCTCTCTGAGACGCCGCATGAATTAATACGTATACTTTGCGCGGGTTCACTGCGATCCGTTCAGAGTCGTCCAAGGGCACAATCGAGCTCCCATTTGTATGTTCGGCTA",
        "build/60x132"),
};

// --- 244x32 tests ---
static const AlignmentTest tests244x32[] = {
  ATEST("ATCG1_244x32",
        "CTCCCACTTAGATTGCCACGCATAGAGCTAGCGAGTCAGCGAAAAGCATGACGCGCTTTCAAGCGTGGCGAGTATGTGAACCAAGGCTTCGGACAGGACTATATACTTAGGTTTGATCTCGCCCCGAGAACTGTAAACCTCAACATTTATAGATTATAAGGTTAGCCGAAAATGCACGTGGTGGCGCCCGCCGACTGCTCCCTGAGTGTGGCTCTTTGTTCTGTCAACGCCCGACCTTCATCGC",
        "CCAATATTTAGTTTCTAAGCCTTGCGACAGAC",
        "build/244x32"),
  ATEST("ATCG2_244x32",
        "GGCCGATTCCTTCTGCGGACCATGTCGTCCTGATACTTTGGCCATGTTTCCGTTGTAGGAGTGAAGCCACTTGGCTTTGCGCCGTAGTTCCAATGAAAAACCTATGGACTTTGTTTAGGGTAGCATCAGGAATCTGAACCCTCAGAAAGTGGGGATCCCGGGTATAGACCTTTATCTGCGGTTCAAGTTAGGCATAAGGCTGCATGCTACCTTGTCACACCTACACTGCTCGAAGTAAATATGG",
        "GTGCGATCCCTGCACCTCAGCTAAGGTAGCTA",
        "build/244x32"),
};

// Flat list of all tests across all sizes — add new arrays here
static const AlignmentTest *all_test_groups[] = {
  tests16x16,
  tests32x32,
  tests32x64,
  tests80x80,
  tests88x88,
  tests60x132,
  tests244x32,
};
static const size_t all_test_group_sizes[] = {
  sizeof(tests16x16) / sizeof(tests16x16[0]),
  sizeof(tests32x32) / sizeof(tests32x32[0]),
  sizeof(tests32x64) / sizeof(tests32x64[0]),
  sizeof(tests80x80) / sizeof(tests80x80[0]),
  sizeof(tests88x88) / sizeof(tests88x88[0]),
  sizeof(tests60x132) / sizeof(tests60x132[0]),
  sizeof(tests244x32) / sizeof(tests244x32[0]),
};
